<%@ Page Title="Comida de Empleado" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="FormComidasEmpleado.aspx.cs" Inherits="Servicios_Reservados_2.FormComidasEmpleado" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <link rel="stylesheet" href="Content/ComidaEmpleado.css" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <nav>
        <ul>
            <li class="item-navegacion"><a href="Default.aspx" title="Página principal"><i class="glyphicon glyphicon-home"></i></a></li>
            <li class="item-navegacion"><a href="FormReservaciones.aspx" title="Reservaciones">Reservaciones</a></li>
            <li class="item-navegacion"><a href="FormEmpleado.aspx" title="Empleados" class="seleccionado">Empleados</a></li>
            <li class="item-navegacion"><a href="FormReportes.aspx" title="Reportes">Reportes</a></li>
            <li class="item-navegacion"><a href="Notificaciones.aspx" title="Notificaciones">Notificaciones <span class="notificacion" id="contador" runat="server">0</span></a></li>
            
        </ul>
    </nav>

    <table>
        <tr>
            <td>
                <legend>
                    <h2>Comida de Empleado</h2>
                </legend>
            </td>
            <td>
                <a href="">
                    <div id="alertAlerta" class="alert alert-danger fade in" runat="server" hidden="hidden">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>
                            <asp:Label ID="labelTipoAlerta" runat="server" Text="Alerta! "></asp:Label></strong><asp:Label ID="labelAlerta" runat="server" Text="Mensaje de alerta"></asp:Label>
                    </div>
                </a>
            </td>
        </tr>
    </table>

    <div class="well bs-component">

        <legend style="color: #7BC143">Información del servicio</legend>
        <table>
            <tr>
                <td>
                Solicitante:
                         <td>
                             <input id="txtNombre" runat="server" style="width: 350px" />
                         </td>
            </tr>

        </table>




        <table>
            <tr>
                <td>
                    <input id="btnEditar" type="button" value="Editar" runat="server" onserverclick="clickModificar" />
                </td>
                <td>
                    <input id="btnAnular" type="button" value="Anular" runat="server" onserverclick="clickEliminar" />
                </td>
            </tr>
        </table>
    </div>

    <div id="ContenedorManejoDeHorario" runat="server" class="well bs-component">
        <div id="selectorDeHorario" runat="server" title="Seleccione el horario de comida">
            <input type="checkbox" id="checkboxDesayuno" runat="server" value="Desayuno" />Desayuno
                        <input type="checkbox" id="checkboxAlmuerzo" runat="server" value="Almuerzo" />Almuerzo
                        <input type="checkbox" id="checkboxCena" runat="server" value="Cena" />Cena
                        <select id="tipodePago" runat="server" title="Seleccione un metodo de pago">
                            <option value="Efectivo">Efectivo</option>
                            <option value="Descuento">Descuento de salario</option>
                        </select>

            <h4>Notas:</h4>
            <textarea id="notas" runat="server" title="Notas">

                            </textarea>
            <h4>Seleccione las fechas en las que desea reservar
            </h4>
            <input type="date" id="fecha" name="fechas" runat="server">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="button" id="btnFecha" class="btn btn-submmit" value="Incluir fecha" runat="server" onserverclick="AgregarFecha_ServerClick" />
        </div>
        <asp:GridView ID="GridFechasReservadas" Class="Gridcontenedor" runat="server" BorderColor="#CCCCCC" BorderStyle="Dotted" BorderWidth="2px" AutoGenerateDeleteButton="False">
            <SelectedRowStyle BackColor="#7BC143" />
        </asp:GridView>


    </div>
    <table>
        <tr>
            <td>
                <input type="button" id="btnAceptar" value="Aceptar" runat="server" onserverclick="clickAceptar" disabled="disabled" />
            </td>
            <td>

                <input type="button" class="btn-danger" value="Cancelar" runat="server" onserverclick="clickCancelar" />
            </td>
        </tr>
    </table>
</asp:Content>
