<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="FormComidasEmpleado.aspx.cs" Inherits="Servicios_Reservados_2.FormComidasEmpleado" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <link rel="stylesheet" href="Content/ComidaEmpleado.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1>Comidas de Empleado <span id="lblEmpleado" runat="server">{nombre Empleado}</span></h1>
    <fieldset class="contenedor">
         

            <div title="Seleccione una operacion sobre las reservaciones de comida" >
             
                <input type="button" value="Agregar" runat="server" onserverclick="clickAgregar"/>
                <input type="button" value="Editar" runat="server" onserverclick="clickModificar"/>
                <input type="button" value="Eliminar" runat="server" onserverclick="clickEliminar"/>
            </div>
            <section id="ContenedorManejoDeHorario" runat="server" class="well">
                    <div id="selectorDeHorario" runat="server" title="Seleccione el horario de comida">
                        <input type="checkbox" id="checkboxDesayuno" runat="server" value="Desayuno" />Desayuno
                        <input type="checkbox" id="checkboxAlmuerzo" runat="server" value="Almuerzo" />Almuerzo
                        <input type="checkbox" id="checkboxCena" runat="server" value="Cena" />Cena
                        <select id="tipodePago" runat="server" title="Seleccione un metodo de pago">
                          <option value="Efectivo">Efectivo</option>
                          <option value="Decuento">Descuento de salario</option>
                        </select>
                    </div>
                    <h4>Notas:</h4>
                    <textarea id="notas" runat="server" title="Notas">

                    </textarea>
                    <h4>
                        Seleccione las fechas en las que desea reservar
                    </h4>
                    <input type="date" id="fecha" name="fechas" runat="server">
                    <input type="button" id="btnFecha" class="btn btn-submmit" value="agregar fecha" runat="server" onserverclick="AgregarFecha_ServerClick"/>
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                     <asp:GridView ID="GridFechasReservadas" runat="server" BorderColor="#CCCCCC" BorderStyle="Dotted" BorderWidth="2px" AutoGenerateDeleteButton="True">
                        <SelectedRowStyle BackColor="#7BC143" />
                     </asp:GridView>

                    </ContentTemplate>
   
                </asp:UpdatePanel>
            </section>
       <input type="button" class="btn-danger" value="Cancelar" runat="server" onserverclick="clickCancelar"/>
       <input type="button" id="btnAceptar" value="Aceptar" runat="server" onserverclick="clickAceptar" disabled="disabled"/>
    </fieldset>
</asp:Content>
